#
# CSE186 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 8 Backend
  version: 0.1.0
  title: CSE186 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Mail Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
  /Mailbox:
    get:
      security:
        - bearerAuth: []
      description: Returns contents of specified mailbox. 
      parameters: 
      - in: query
        name: mailbox
        schema:
          type: string
        required: false
        description: Mailbox name
      responses:
        200:
          description: Mail Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMailbox'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

components:
  schemas:
    UnexpectedError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    User:
      type: object
      properties:
        name:
          type: string
        accessToken:
          type: string
      required:
        - name
        - accessToken


    GetMailbox:
      type: array
      items:
        $ref: '#/components/schemas/GetMailbox2'

    GetMailbox2:
      type: object
      properties:
        mail:
          type: object
          items:
            $ref: '#/components/schemas/Getmailbox3'
      required:
        - mailbox
        - mail

    Getmailbox4:
      type: object
      additionalProperties: false
      properties:
        Owner:
          type: string
        Name:
          type: string
          
    Getmailbox3:
      type: object
      additionalProperties: false
      properties:
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        sent:
          type: string
        subject:
          type: string
        received:
          type: string
        content:
          type: string
        Mailbox:
          type: string

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes