--
-- All SQL statements must be on a single line and end in a semicolon.
--

-- Populate Your Tables Here --
INSERT INTO users(Name, EMail_address, Password_hash) VALUES ('Molly Member','molly@books.com','$2b$10$Y00XOZD/f5gBSpDusPUgU.iJufk6Nxx6gAoHRG8t2eHyGgoP2bK4y');
INSERT INTO users(Name, EMail_address, Password_hash) VALUES ('Anna Admin','anna@books.com','$2b$10$Y00XOZD/f5gBSpDusPUgU.G1ohpR3oQbbBHK4KzX7dU219Pv/lzze');

-- Tables populated for mailbox, content generated using randomwordgenerator below --
-- https://randomwordgenerator.com/paragraph.php --
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Dwayne","email":"dwayne@rock.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-12-01T23:00:00Z","sent":"2022-11-30T23:00:00Z","content":"Generating random paragraphs can be an excellent way for writers to get their creative flow going at the beginning of the day. The writer has no idea what topic the random paragraph will be about when it appears. This forces the writer to use creativity to complete one of three common writing challenges. The writer can use the paragraph as the first one of a short story and build upon it. A second option is to use the random paragraph somewhere in a short story they create. The third option is to have the random paragraph be the ending paragraph in a short story. No matter which of these challenges is undertaken, the writer is forced to use creativity to incorporate the paragraph into their writing.\n\nGenerating random paragraphs can be an excellent way for writers to get their creative flow going at the beginning of the day. The writer has no idea what topic the random paragraph will be about when it appears. This forces the writer to use creativity to complete one of three common writing challenges. The writer can use the paragraph as the first one of a short story and build upon it. A second option is to use the random paragraph somewhere in a short story they create. The third option is to have the random paragraph be the ending paragraph in a short story. No matter which of these challenges is undertaken, the writer is forced to use creativity to incorporate the paragraph into their writing.","subject":"Dwayne the Rock Wants to Speak"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Rock","email":"yesterday@yes.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-11-25T23:00:00Z","sent":"2022-11-25T23:00:00Z","content":"I love rocks, you should too","subject":"Rocks??"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Another person","email":"ap@gmail.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-11-10T23:00:00Z","sent":"2022-11-10T23:00:00Z","content":"This message was sent sometime in the month, look at it","subject":"Sometime in the month"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Chicken Rice Man","email":"crice@me.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-10-12T23:17:19Z","sent":"2022-10-12T17:09:17Z","content":"The red ball sat proudly at the top of the toybox. It had been the last to be played with and anticipated it would be the next as well. The other toys grumbled beneath. At one time each had held the spot of the red ball, but over time they had sunk deeper and deeper into the toy box.","subject":"Red Ball"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"The Light Man","email":"tl@;light.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-08-12T23:17:19Z","sent":"2022-08-12T17:09:17Z","content":"The light blinded him. It was dark and he thought he was the only one in the area, but the light shining in his eyes proved him wrong. It came from about 100 feet away and was shining so directly into his eyes he couldnt make out anything about the person holding the light. There was only one thing to do in this situation. He reached into his pocket and pulled out a flashlight of his own that was much stronger than the one currently blinding him. He turned it on and pointed it into the strangers eyes.","subject":"The Light"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Sand Castle Man","email":"sc@castle.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-05-03T23:17:19Z","sent":"2022-05-03T17:09:17Z","content":"The wave crashed and hit the sandcastle head-on. The sandcastle began to melt under the waves force and as the wave receded, half the sandcastle was gone. The next wave hit, not quite as strong, but still managed to cover the remains of the sandcastle and take more of it away. The third wave, a big one, crashed over the sandcastle completely covering and engulfing it. When it receded, there was no trace the sandcastle ever existed and hours of hard work disappeared forever.","subject":"sandcastle"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2020-11-14T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"This is a test entry","subject":"TEST Entry"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Green Vine Man","email":"gv@vine.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-03-03T23:17:19Z","sent":"2022-03-03T17:09:17Z","content":"Green vines attached to the trunk of the tree had wound themselves toward the top of the canopy. Ants used the vine as their private highway, avoiding all the creases and crags of the bark, to freely move at top speed from top to bottom or bottom to top depending on their current chore. At least this was the way it was supposed to be. Something had damaged the vine overnight halfway up the tree leaving a gap in the once pristine ant highway.","subject":"Green Vines on the Creek"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Wolf Man","email":"wm@wolf.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-02-17T23:17:19Z","sent":"2022-02-17T17:09:17Z","content":"The wolves stopped in their tracks, sizing up the mother and her cubs. It had been over a week since their last meal and they were getting desperate. The cubs would make a good meal, but there were high risks taking on the mother Grizzly. A decision had to be made and the wrong choice could signal the end of the pack..","subject":"Wolves in the woods"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Random Man","email":"random@man.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-02-14T23:17:19Z","sent":"2022-02-17T17:09:14Z","content":"Where do they get a random paragraph? he wondered as he clicked the generate button. Do they just write a random paragraph or do they get it somewhere? At that moment he read the random paragraph and realized it was about random paragraphs and his world would never be the same.","subject":"The Randomness"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Your Wife Probably","email":"your@wife.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-02-05T23:17:19Z","sent":"2022-02-17T17:09:05Z","content":"It was supposed to be a dream vacation. They had planned it over a year in advance so that it would be perfect in every way. It had been what they had been looking forward to through all the turmoil and negativity around them. It had been the light at the end of both their tunnels. Now that the dream vacation was only a week away, the virus had stopped all air travel.","subject":"Dream Vacation Maybe?"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Inbox","from":{"name":"Your Wife Probably","email":"your@wife.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2021-02-06T23:17:19Z","sent":"2021-02-06T17:09:05Z","content":"It was supposed to be a dream vacation. They had planned it over a year in advance so that it would be perfect in every way. It had been what they had been looking forward to through all the turmoil and negativity around them. It had been the light at the end of both their tunnels. Now that the dream vacation was only a week away, the virus had stopped all air travel.","subject":"Dream Vacation Maybe????????"}');

INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Trash","from":{"name":"Jonathan Boneparte","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-11-15T23:17:19Z","sent":"2022-11-15T17:09:17Z","content":"We are in the trash","subject":"Trash message 2022"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Trash","from":{"name":"Jonathan Boneparty","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-10-04T23:17:19Z","sent":"2022-10-04T17:09:17Z","content":"We are in the trash","subject":"Trash message from earlier"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Trash","from":{"name":"Jonathan Bonepartay","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2021-11-15T23:17:19Z","sent":"2021-11-15T17:09:17Z","content":"We are in the trash","subject":"Sus"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Trash","from":{"name":"Jonathan Bonepartie","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2020-11-15T23:17:19Z","sent":"2020-11-15T17:09:17Z","content":"We are in the trash","subject":"Are"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Trash","from":{"name":"Jonathan Boneparto","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2019-11-15T23:17:19Z","sent":"2019-11-15T17:09:17Z","content":"We are in the trash","subject":"You"}');

INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Sent","from":{"name":"Sent Man","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-11-20T23:17:19Z","sent":"2022-11-20T23:17:19Z","content":"We are in Sent","subject":"We have to make a lot of emails"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Sent","from":{"name":"I am the sent Man","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2022-01-01T23:17:19Z","sent":"2022-01-01T23:17:19Z","content":"We are in Sent","subject":"After inbox I gave up on making content"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Sent","from":{"name":"Thanks for the hard work","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2021-11-15T23:17:19Z","sent":"2021-11-15T17:09:17Z","content":"We are in Sent","subject":"This assignment is fun tho"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Sent","from":{"name":"I sent thee","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2020-11-12T23:17:19Z","sent":"2020-11-12T17:09:17Z","content":"We are in Sent","subject":"Thanks for your hard work"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"molly@books.com","Name":"Molly Member"}','{"Mailbox":"Sent","from":{"name":"Solo bolo","email":"jbone@myspace.com"},"to":{"name":"Molly Member","email":"molly@books.com"},"received":"2019-11-11T23:17:19Z","sent":"2019-11-11T17:09:17Z","content":"We are in Sent","subject":"Still getting stuff graded even through finals"}');

INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Inbox","from":{"name":"Jacob Buck","email":"jbuck@myspace.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-11-12T23:11:19Z","sent":"2022-11-12T17:09:17Z","content":"Please meet me under the window at 10","subject":"I want to speak"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Inbox","from":{"name":"Happy Guy","email":"happy@happy.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-10-01T23:11:19Z","sent":"2022-10-01T17:09:17Z","content":"You are a good person","subject":"You are a good person"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Inbox","from":{"name":"Hi Person","email":"happy@happy.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-09-28T23:11:19Z","sent":"2022-09-28T17:09:17Z","content":"Hi","subject":"Hello There"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Inbox","from":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2020-11-13T23:12:19Z","sent":"2020-11-13T17:09:17Z","content":"This is a test entry 3","subject":"TEST Entry 3"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Inbox","from":{"name":"Colonel Sanders","email":"colonel@myspace.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2010-11-13T23:12:19Z","sent":"2010-11-13T17:09:17Z","content":"Eat my fried chicken","subject":"Fried Chicken is Good"}');


INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Trash","from":{"name":"Buck Jacob","email":"jbuck@trash.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-11-18T23:11:19Z","sent":"2022-11-18T17:09:17Z","content":"Happy Feet is a popular movie from the 2000s","subject":"Happy Feet"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Trash","from":{"name":"Guy Happy","email":"happy@trash.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-10-08T23:11:19Z","sent":"2022-10-08T17:09:17Z","content":"asdfsdn","subject":"Wombo Combo"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Trash","from":{"name":"Person Hi","email":"happy@trash.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-09-23T23:11:19Z","sent":"2022-09-23T17:09:17Z","content":"hi","subject":"OOH OOH"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Trash","from":{"name":"Rheam Shandra","email":"srheam0@trash.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2020-11-15T23:12:19Z","sent":"2020-11-15T17:09:17Z","content":"fake","subject":"FAKER WITH THE HUGE OUTPLAY"}');


INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Sent","from":{"name":"Tired","email":"tired@sent.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-11-18T23:11:19Z","sent":"2022-11-18T17:09:17Z","content":"Happy Feet is a popular movie from the 2000s","subject":"Super"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Sent","from":{"name":"REally tired","email":"really@sent.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-10-08T23:11:19Z","sent":"2022-10-08T17:09:17Z","content":"Smash bros brawl","subject":"Smash"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Sent","from":{"name":"Fun assignment tho","email":"fun@sent.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2022-09-23T23:11:19Z","sent":"2022-09-23T17:09:17Z","content":"not brothers, BROTHERS","subject":"Brothers"}');
INSERT INTO mail(mailbox, mail) VALUES ('{"Owner":"anna@books.com","Name":"Anna Admin"}','{"Mailbox":"Sent","from":{"name":"Lotsa work","email":"work@sent.com"},"to":{"name":"Anna Admin","email":"anna@books.com"},"received":"2020-11-15T23:12:19Z","sent":"2020-11-15T17:09:17Z","content":"sheeeee","subject":"Ultimate"}');